### ISSUE TITLE
deps: `dicom-parser`

### ISSUE THREAD

**Issue by jjjermiah** [bhklab/readii#41]
Wondering if the `dicom-parser` library is still required:
- besides an extra dependency, it is one of the deps that restrict `pydicom` with [pydicom](https://github.com/pydicom/pydicom) now at `>v3.0`, will deal with imgtools later 

It seems to only be used once to load a Series and pull some metadata from it:

https://github.com/bhklab/readii/blob/3b57b49cedbced3d2a668a6257b62a4e6cb4026a/src/readii/image_processing.py#L117-L149

Wondering if this functionality is too difficult to extract from the loaders built into Readii already? 

If too much work, we can ignore this lol

**Comment by strixy16** [comment]
That function is specifically for images that have mismatched dimensions. I specifically need information from the DICOM header, which isn't something that I could easily get from the med-imagetools image loaders at the time. Could be something we solve when we update MIT and READII 2.0.

**Comment by skim2257** [comment]
it seems the Series() class is used to index first and last instanceUIDs, which is already stored when crawling, but it's only saved in _imgtools.json
