### ISSUE TITLE
Implementing the nifti loading stuff

### ISSUE THREAD

**Issue by jjjermiah** [bhklab/readii#44]
Couple of questions: 

1. What needs to be done/whats blocking the nifti implementation?

2. Other than the loaders, what does the nifti implementation change in the process?

    - From my understanding, it looks like at some point the readii workflow looks to create a `sitk.Image` before the actual feature extraction process
    - So is it safe to assume that as long as the niftis get loaded into this format, there wouldnt be any other changes? 
        - would all the preprocessing steps (flatten, align) still apply to the images loaded from niftis?

- [ ] #45

**Comment by strixy16** [comment]
When we initially tried implementing the nifti loading, Mogtaba found that something was off with the images that had been converted by med-imagetools. So we need to implement some kind of checking to make sure that the image hasn't been corrupted somehow, probably in the conversion step.

If we assume that the nifti is correct, then yes it just needs to be loaded and put into a sitk.Image. 
Flatten handles when segmentations sometimes have a fourth dimension that just has a single value. This value usually represents time, but we need to remove it to align it with the main image (CT/MRI). So we still need it.

Align is a necessary for pyradiomics to work. Their code checks for this alignment and will break if the direction/origin/spacing don't match. It currently runs always, even if the alignment does match, just to ensure pyradiomics runs.
