### ISSUE TITLE
need some kind of logger documentation

### ISSUE THREAD

**Issue by strixy16** [bhklab/readii#60]
I imported readii into another project and am running some of the functions and I keep getting these log directories and files created every time I run a function in a different Jupyter notebook cell. I need some kind of explanation on how it's supposed to work, how to disable it, set levels of verbosity, etc.

**Comment by jjjermiah** [comment]
weird, the logging stuff is a work in progress not on the main branch

oddly pypi has a version 1.14.2 but it was never released on github 

I've forced a new release at 1.16.0 can you try that and let me know if that goes back to normal

**Comment by strixy16** [comment]
Should probably think about making a mkdocs or something for documentation of the package.
